version: '3.8'

services:
    app:
        build:
            context: . # مسیری که Dockerfile در آن قرار دارد
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "9000:9000" # پورت PHP-FPM
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel_nginx
        volumes:
            - .:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
